version: "3.3"
services:
  server:
    build: .
    container_name: node-server
    image: node-server
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - mongo
      - mongo-express
  mongo:
    image: mongo
    networks:
      - backend
    ports:
      - "27017:27017"
    container_name: db
    environment:
      "MONGO_INITDB_ROOT_USERNAME": root
      "MONGO_INITDB_ROOT_PASSWORD": F235vk26
      "MONGO_INITDB_DATABASE": aiman
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - backend
    ports:
      - "8081:8081"
    container_name: mongo-express
    environment:
      "ME_CONFIG_MONGODB_SERVER": db
      "ME_CONFIG_MONGODB_PORT": 27017
      "ME_CONFIG_MONGODB_ADMINUSERNAME": root
      "ME_CONFIG_MONGODB_ADMINPASSWORD": F235vk26
    depends_on:
      - mongo
networks:
    backend:
